[Style] Maj description des profils, ajout contributeurs, ajout page liste des profils
Interop-Sante/hl7.fhir.fr.core pull request #146
Opened 2024-03-21 09:48 UTC by nriss

## Description des changements | Description of changes made

* Mise à jour de la description de chaque profil (saut de ligne plutôt que des pipes)
* Ajout des contributeurs (Sylvain, Marie, Isabelle)
* Ajout d'une page "liste des profils"
* Mise à jour des workflows et du pr template
* Mise à jour de la dépendance NOS à 1.2.0

## Preview

https://interop-sante.github.io/hl7.fhir.fr.core/nr-add-profile-list/ig

2024-03-21 10:42 UTC, mbrulliard commented on input/fsh/profiles/FRCoreObservationBpProfile.fsh
> +\r\nProfil français de pression artérielle avec tous les éléments fils optionnels. Il s'agit d'une Observation avec l'élément Observation.valueQuantity n'est pas renseigné et qui contient au moins un
Par rapport aux autres profils, cette définition n'est pas très claire et ne correspond pas aux contraintes, non ?

2024-03-21 10:47 UTC, nriss commented on input/fsh/profiles/FRCoreObservationBpProfile.fsh
> +\r\nProfil français de pression artérielle avec tous les éléments fils optionnels. Il s'agit d'une Observation avec l'élément Observation.valueQuantity n'est pas renseigné et qui contient au moins un
Je suis d'accord! J'ai pas modifié le contenu, juste la structure
Je vais simplifier la description, les contraintes sont dans le profil, pas besoin de les répéter dans la description à mon sens :)

2024-03-21 11:05 UTC, mbrulliard approved these changes

2024-03-22 10:21 UTC, sdemeyANS requested changes

2024-03-22 10:21 UTC, sdemeyANS commented on input/fsh/profiles/FRCoreSlotProfile.fsh
> +Description: """Profil of the Slot resource for france.\r\n
majuscule pour france ?

2024-03-22 10:21 UTC, sdemeyANS commented on sushi-config.yaml
> +  ans.fr.nos: latest
pas risqué si des JDV/TRE sont retirées lors des publications mensuelles ou si des url changent?

2024-03-22 10:25 UTC, sdemeyANS commented on input/pagecontent/profile_list.md
les URL canonique du profil parent renvoient vers R5. Pas un risque de confusion?

2024-03-22 10:27 UTC, nriss commented on input/pagecontent/profile_list.md
C'est pour ça que j'ai mis "URL canonique du profil parent", je peux enlever la colonne à la limite mais je vois pas d'autre solution

2024-03-25 10:11 UTC, ypoiron approved these changes

2024-03-25 10:17 UTC, sdemeyANS reviewed
une petite remarque :)

2024-03-25 10:17 UTC, sdemeyANS commented on sushi-config.yaml
> +  ans.fr.nos: 1.2.0
pas d'impact sur dtte version avec potentiellement des TRE / jdv retired ?

2024-03-25 10:36 UTC, sdemeyANS approved these changes

2024-03-25 10:41 UTC, merged