Update url
Interop-Sante/hl7.fhir.fr.core pull request #152
Opened 2024-04-03 12:46 UTC by nriss

## Description des changements | Description of changes made

* Anciennes URLs interopsanté changées avec la nouvelle

## Preview

https://interop-sante.github.io/hl7.fhir.fr.core/[ajouter_nom_de_la_branche]/ig

2024-04-03 13:01 UTC, sdemeyANS approved these changes

2024-04-04 09:14 UTC, sdemeyANS approved these changes
c'est bon pour tous les autres profils ?

2024-04-04 09:51 UTC, nriss commented
J'ai cherché "interopsante.org", pas de traces restantes

2024-04-11 09:15 UTC, sdemeyANS approved these changes

2024-04-11 09:18 UTC, sdemeyANS requested changes

2024-04-11 09:18 UTC, sdemeyANS commented on input/fsh/profiles/FRCoreOrganizationProfile.fsh
> +    https://hl7.org/fhir/StructureDefinition/organization-period named usePeriod 0..1
error Cannot create usePeriod extension; unable to locate extension definition for: https://hl7.org/fhir/StructureDefinition/organization-period.
  File: /home/runner/work/hl7.fhir.fr.core/hl7.fhir.fr.core/igSource/input/fsh/profiles/FRCoreOrganizationProfile.fsh
  Line: 18 - 22
error No element found at path extension[usePeriod] for CardRule in FRCoreOrganizationProfile, skipping rule
  File: /home/runner/work/hl7.fhir.fr.core/hl7.fhir.fr.core/igSource/input/fsh/profiles/FRCoreOrganizationProfile.fsh
  Line: 18 - 22

2024-04-11 09:22 UTC, nriss commented on input/fsh/profiles/FRCoreOrganizationProfile.fsh
> +    https://hl7.org/fhir/StructureDefinition/organization-period named usePeriod 0..1
Réparé

2024-04-11 09:47 UTC, sdemeyANS approved these changes
ok :)

2024-04-16 08:54 UTC, merged